config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create]  do
    resources :bookmarks, only: [:new, :create]
  end
    resources :bookmarks, only: [:destroy]
  # :movies, :bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  private 
  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all.order(:title), prompt: 'Select a movie', input_html: { class: 'select2' } %>
  <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
  <%= f.submit class: 'btn btn-flat' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1532568547949-a09f1afe4d1b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80);">
  <div class="container">
    <h1 class="text-center" ><strong>Creative people</strong></h1>
  </div>
</div>

<div class="container py-5">
  <h1> Listas </h1>
  <div class="row justify-content-end"> <%= link_to "create", new_list_path(@list), :class => "btn btn-primary" %> </div>
  
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1622976479615-38700d470a1c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=849&q=80)">
        <p> <%= link_to list.name, list_path(list), class: "text-white" %> </p>
      </div>
    <% end %>
  </div>
  
</div>

app/views/lists/new.html.erb
<div class="cointainer">

<h1> Create your list </h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name, placeholder: "Name" %>
  <%= f.submit "create" %>
<% end %>

</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80);">
  <div class="container">
    <h1 class="text-center pb-3"> <%= @list.name %> </h1>
    <h2 class="text-center"><strong>Enjoy some reviews</strong></h2>
  </div>
</div>

<div class="container mt-5">
  <h2> Content </h2>

  <div class="row justify-content-end"> <%= link_to "Add a movie", list_path, :class => "btn btn-primary"%> </div>
  <div class="row justify-content-end"> <%= link_to "comment", new_list_bookmark_path(@list), :class => "btn btn-primary" %> </div>

    <div class=cards>
      <% @list.bookmarks.each do |bookmark| %>
        <div class="card">
          <img src= <%= bookmark.movie.poster_url %> />
            <div class="card-i">
              <div class="card-info">
                <p class="mt-0 mb-2"> <strong> <%= bookmark.movie.title %> </strong> </p>
                <p class="mb-2"> <%= bookmark.movie.overview %> </p>
              </div>
              
              <p class="mb-2"> <%= bookmark.movie.rating %> </p>
              <small> <%= bookmark.comment %> </small>
              <p class="text-right"> <%= link_to "delete", bookmark_path, method: :delete %> </p>
            </div>
        </div>
      <% end %>
    </div>

  <%#= link_to "Ver Bookmarks", bookmark_path(@bookmarks) %>
</div>